/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SatisfactionRouteImport } from './routes/satisfaction'
import { Route as IndexRouteImport } from './routes/index'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SatisfactionRoute = SatisfactionRouteImport.update({
  id: '/satisfaction',
  path: '/satisfaction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/satisfaction': typeof SatisfactionRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/satisfaction': typeof SatisfactionRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/satisfaction': typeof SatisfactionRoute
  '/transfer': typeof TransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/satisfaction' | '/transfer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/satisfaction' | '/transfer'
  id: '__root__' | '/' | '/satisfaction' | '/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SatisfactionRoute: typeof SatisfactionRoute
  TransferRoute: typeof TransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satisfaction': {
      id: '/satisfaction'
      path: '/satisfaction'
      fullPath: '/satisfaction'
      preLoaderRoute: typeof SatisfactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SatisfactionRoute: SatisfactionRoute,
  TransferRoute: TransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
